Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Models/OrderCostSummary.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace PartsUnlimited.ViewModels
{
    public class OrderCostSummary
    {
        public string CartSubTotal { get; set; }
        public string CartShipping { get; set; }
        public string CartTax { get; set; }
        public string CartTotal { get; set; }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Areas/Admin/Controllers/CustomerController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using PartsUnlimited.Models;
using System.Linq;
using System.Threading.Tasks;

namespace PartsUnlimited.Areas.Admin.Controllers
{
    public class CustomerController : AdminController
    {
        private readonly IPartsUnlimitedContext _context;

        public CustomerController(IPartsUnlimitedContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return Redirect(nameof(Find));
            }

            var user = await _context.Users.SingleOrDefaultAsync(u => u.Id == id);

            if (user == null)
            {
                return Redirect(nameof(Find));
            }

            return View(user);
        }

        public async Task<IActionResult> Find(string username, string email, string phoneNumber)
        {
            IQueryable<ApplicationUser> query = _context.Users;

            if (!string.IsNullOrWhiteSpace(username))
            {
                query = query.Where(u => u.UserName == username);
            }

            if (!string.IsNullOrWhiteSpace(email))
            {
                query = query.Where(u => u.Email == email);
            }

            if (!string.IsNullOrWhiteSpace(phoneNumber))
            {
                query = query.Where(u => u.PhoneNumber == phoneNumber);
            }

            // We only want cases where there is one instance.  SingleOrDefault will throw an exception
            // when there is more than one, so we take two and only use the result if it was the only one
            var result = await query.Take(2).ToListAsync();

            if (result.Count == 1)
            {
                return RedirectToAction(nameof(Index), new { id = result[0].Id });
            }

            return View();
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Areas/Admin/Controllers/OrdersController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Mvc;
using PartsUnlimited.Queries;
using PartsUnlimited.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PartsUnlimited.Areas.Admin.Controllers
{
    public class OrdersController : AdminController
    {
        private readonly IOrdersQuery _ordersQuery;

        public OrdersController(IOrdersQuery ordersQuery)
        {
            _ordersQuery = ordersQuery;
        }

        public async Task<IActionResult> Index(string username, DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            return View(await _ordersQuery.IndexHelperAsync(username, start, end, 10, invalidOrderSearch, true));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = Request.Query["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);

            if (order == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }
            var itemsCount = order.OrderDetails.Sum(x => x.Quantity);
            var subTotal = order.OrderDetails.Sum(x => x.Quantity * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Controllers/OrdersController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;
using PartsUnlimited.Queries;
using PartsUnlimited.Telemetry;
using PartsUnlimited.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersQuery _ordersQuery;
        private readonly ITelemetryProvider _telemetry;

        public OrdersController(IOrdersQuery ordersQuery, ITelemetryProvider telemetryProvider)
        {
            _ordersQuery = ordersQuery;
            _telemetry = telemetryProvider;
        }

        public async Task<IActionResult> Index(DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            var username = User.GetUserName();

            return View(await _ordersQuery.IndexHelperAsync(username, start, end, 10, invalidOrderSearch, false));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                _telemetry.TrackTrace("Order/Server/NullId");
                return RedirectToAction("Index", new { invalidOrderSearch = Request.Query["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);
            var username = User.GetUserName();

            // If the username isn't the same as the logged in user, return as if the order does not exist
            if (order == null || !String.Equals(order.Username, username, StringComparison.Ordinal))
            {
                _telemetry.TrackTrace("Order/Server/UsernameMismatch");
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }

            // Capture order review event for analysis
            var eventProperties = new Dictionary<string, string>()
                {
                    {"Id", id.ToString() },
                    {"Username", username }
                };
            if (order.OrderDetails == null)
            {
                _telemetry.TrackEvent("Order/Server/NullDetails", eventProperties, null);
            }
            else
            {
                var eventMeasurements = new Dictionary<string, double>()
                {
                    {"LineItemCount", order.OrderDetails.Count }
                };
                _telemetry.TrackEvent("Order/Server/Details", eventProperties, eventMeasurements);
            }

            var itemsCount = order.OrderDetails.Sum(x => x.Quantity);
            var subTotal = order.OrderDetails.Sum(x => x.Quantity * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Controllers/SearchController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Mvc;
using PartsUnlimited.Search;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    public class SearchController : Controller
    {
        private readonly IProductSearch _search;

        public SearchController(IProductSearch search)
        {
            _search = search;
        }

        public async Task<IActionResult> Index(string q)
        {
            if (string.IsNullOrWhiteSpace(q))
            {
                return View(null);
            }

            var result = await _search.Search(q);

            return View(result);
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Controllers/ShoppingCartController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Antiforgery;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Primitives;
using PartsUnlimited.Models;
using PartsUnlimited.Telemetry;
using PartsUnlimited.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PartsUnlimited.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly ITelemetryProvider _telemetry;
        private readonly IAntiforgery _antiforgery;
        private readonly IProductsRepository productsRepository;
        
        public ShoppingCartController(IPartsUnlimitedContext context, ITelemetryProvider telemetryProvider, IAntiforgery antiforgery, IProductsRepository productsRepository)
        {
            _db = context;
            _telemetry = telemetryProvider;
            _antiforgery = antiforgery;
            this.productsRepository = productsRepository;
        }

        //
        // GET: /ShoppingCart/

        public IActionResult Index()
        {
            var cart = ShoppingCart.GetCart(_db, this.productsRepository, HttpContext);

            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };


            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = items,
                CartCount = itemsCount,
                OrderCostSummary = costSummary
            };

            // Track cart review event with measurements
            _telemetry.TrackTrace("Cart/Server/Index");

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5

        public async Task<IActionResult> AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = this.productsRepository.GetById(id);

            // Start timer for save process telemetry
            var startTime = System.DateTime.Now;

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(_db, this.productsRepository, HttpContext);

            cart.AddToCart(addedProduct);

            await _db.SaveChangesAsync(HttpContext.RequestAborted);

            // Trace add process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", System.DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            _telemetry.TrackEvent("Cart/Server/Add", null, measurements);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            // Start timer for save process telemetry
            var startTime = System.DateTime.Now;

            // Retrieve the current user's shopping cart
            var cart = ShoppingCart.GetCart(_db, this.productsRepository, HttpContext);

            // Get the name of the product to display confirmation
            // TODO [EF] Turn into one query once query of related data is enabled
            int productId = _db.CartItems.Single(item => item.CartItemId == id).ProductId;
            string productName = this.productsRepository.GetById(productId).Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            await _db.SaveChangesAsync(HttpContext.RequestAborted);

            string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;

            // Trace remove process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", System.DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            _telemetry.TrackEvent("Cart/Server/Remove", null, measurements);

            // Display the confirmation message
            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var results = new ShoppingCartRemoveViewModel
            {
                Message = removed + productName +
                    " has been removed from your shopping cart.",
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C"),
                CartCount = itemsCount,
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Controllers/StoreController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.Caching.Memory;
using PartsUnlimited.Models;
using System;
using System.Linq;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly IMemoryCache _cache;
        private readonly IProductsRepository productsRepository;

        public StoreController(IPartsUnlimitedContext context, IMemoryCache memoryCache, IProductsRepository productsRepository)
        {
            _db = context;
            _cache = memoryCache;
            this.productsRepository = productsRepository;
        }

        //
        // GET: /Store/

        public IActionResult Index()
        {
            var category = _db.Categories.ToList();

            return View(category);
        }

        //
        // GET: /Store/Browse?category=Brakes

        public IActionResult Browse(int categoryId)
        {
            // Retrieve Category category and its Associated associated Products products from database

            // TODO [EF] Swap to native support for loading related data when available
            var categoryModel = _db.Categories.Single(g => g.CategoryId == categoryId);
            categoryModel.Products = this.productsRepository.Find(a => a.CategoryId == categoryModel.CategoryId).ToList();

            return View(categoryModel);
        }

        public IActionResult Details(int id)
        {
            Product productData;

            if (!_cache.TryGetValue(string.Format("product_{0}", id), out productData))
            {
                productData = this.productsRepository.GetById(id);
                productData.Category = _db.Categories.Single(g => g.CategoryId == productData.CategoryId);

                if (productData != null)
                {
                    _cache.Set(string.Format("product_{0}", id), productData, new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromMinutes(10)));
                }                
            }

            return View(productData);
        }
    }
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/DemoLinkDisplay.cshtml
@{
    ViewBag.Title = "Demo link display page - Not for production use";
}

<section>
    <h2>@ViewBag.Title</h2>
    <div class="row">
        <div class="col-md-6">
            <div>
                <p>
                    Demo link display page - Not for production use.
                </p>

                @if (ViewBag.Link != null)
                {
                    <p class="text-danger">
                        For DEMO only: You can click this link to confirm the email: [[<a href="@ViewBag.Link">link</a>]]
                        <br />
                        Please change this code to register an email service in IdentityConfig to send an email.
                    </p>
                }
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
</section>

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/_AdminMenu.cshtml
@using PartsUnlimited.Areas.Admin

@{
    var claims = User.Identity as System.Security.Claims.ClaimsIdentity;
    var isAdmin = claims.HasClaim(AdminConstants.ManageStore.Name, AdminConstants.ManageStore.Allowed);
}

@if (isAdmin)
{
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="admin-link" class="dropdown-toggle head-link" data-toggle="dropdown">Admin&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li> @Html.ActionLink("Manage Items", "Index", "StoreManager", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("View Orders", "Index", "Orders", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("Find Customers", "Find", "Customer", new { area = AdminConstants.Area }) </li>
            <li> @Html.ActionLink("View Rainchecks", "Index", "Raincheck", new { area = AdminConstants.Area }) </li>
        </ul>
    </li>
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/_Layout.cshtml
@using PartsUnlimited
@inject Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment RuntimeEnvironment
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Parts Unlimited</title>
    @await Component.InvokeAsync("Configuration")
    @Html.Styles("bootstrap")
    @Html.Styles("jquery-ui")
    @Html.Styles("site")
    @Html.Script("modernizr")
    @Html.Script("jquery")
</head>
<body>
    <header>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="primary-menu">
                    <div class="pull-left logo">
                        <a class="block logo-image" href="@Url.Action("Index", "Home")">
                            @Html.Image("unlimited_logo.png", "Parts Unlimited logo")
                        </a>
                        <a class="block" href="@Url.Action("Index", "Home")">
                            <h1>Parts Unlimited</h1>
                            <h2>a Fabrikam subsidiary</h2>
                        </a>
                        <div class="visible-xs cart">
                            <a href="@Url.Action("Index", "ShoppingCart")" class="head-link" id="shopping-cart-link"></a>
                        </div>
                    </div>
                    <div class="pull-right navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-header-nav">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="collapse-header-nav">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="hidden-xs">
                                    <div id="search-link-box">
                                        @using (Html.BeginForm("Index", "Search", FormMethod.Get))
                                        {
                                            @Html.TextBox("q", null, new { @class = "form-control", id = "search-box", placeholder = "Keyword" })
                                            <input type="submit" id="search-link" value="Search" />
                                        }
                                    </div>
                                </li>
                                <li><a href="@Url.Action("Index", "Home")" class="head-link" id="home-link">Home</a></li>
                                @await Component.InvokeAsync("CartSummary")
                                @await Html.PartialAsync("_AdminMenu")
                                @await Html.PartialAsync("_Login")
                                <li class="dropdown visible-xs">
                                    <a href="@Url.Action("Index", "Store")" class="dropdown-toggle head-link" data-toggle="dropdown">Categories&nbsp;<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        @await Component.InvokeAsync("CategoryMenu")
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="category-menu">
                <div class="container">
                    <div class="hidden-xs">
                        <ul>
                            @await Component.InvokeAsync("CategoryMenu")
                        </ul>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("Announcement")
        </nav>
        <div class="visible-xs search-box">
            @using (Html.BeginForm("Index", "Search", FormMethod.Get))
            {
                @Html.TextBox("q", null, new { @class = "form-control", placeholder = "Search" })
                <input type="submit" value="" />
            }
        </div>
    </header>
    @RenderSection("prebody", false)
    <div class="container">
        @RenderBody()
    </div>
    <div class="clearfix"></div>
    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="row">
                    <div class="col-md-3">
                        <h4>Site Menu</h4>
                        <ul>
                            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><a href="@Url.Action("Index", "Store")">Browse</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Account</h4>
                        <ul>
                            <li>@Html.ActionLink("Manage Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                            <li>@Html.ActionLink("Shopping Cart", "Index", "ShoppingCart")</li>
                            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty })</li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Additional Info</h4>
                        <ul>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms and Conditions</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Develop</h4>
                        <ul>
                            <li><a>GitHub Source</a></li>
                            <li><a>License Agreement</a></li>
                            <li><a href="http://asp.net/" target="_blank">ASP.NET</a></li>
                        </ul>
                        <p>Deploy to Azure</p>
                        <a class="deploy-azure">
                            @Html.Image("deploy_button.png", "deploy to azure image")
                        </a>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-6">
                        <div class="pull-left-sm">
                            © @DateTime.UtcNow.Year Microsoft. Based on The Phoenix Project by <a href="http://www.realgenekim.me/" class="footer-link">Gene Kim</a>.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-left-sm pull-right-md">
                            All rights reserved. Your payments are safe and secure.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="text-center">
                        Site powered by @RuntimeEnvironment.OperatingSystem @RuntimeEnvironment.OperatingSystemVersion and running on @RuntimeEnvironment.RuntimeType @RuntimeEnvironment.RuntimeVersion
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @Html.Script("jquery-ui")
    @Html.Script("bootstrap")
    @Html.Script("bootstrap-switch")
    @Html.Script("signalr")
    @Html.Script("signalr-hubs")
    @Html.Script("site")
    @Html.Script("respond")
    @RenderSection("scripts", required: false)
</body>
</html>

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/_Login.cshtml
@using System.Security.Principal

@if (User.Identity.IsAuthenticated)
{
    var isNtlm = User.Identity.AuthenticationType == "NTLM";
    
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="profile-link" class="dropdown-toggle head-link" data-toggle="dropdown">Profile&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Manage Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty })</li>
            @if (!isNtlm)
            {
            <li>
                @*Either NTLM will be used or social authentication will be used. Based on the authentication schemes enabled remove an unused block.*@
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                }
                <a href="javascript:document.getElementById('logoutForm').submit()" >Log off</a>
            </li>
            }
        </ul>
    </li>
}
else
{
    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "login-link", @class = "head-link" })</li>
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/_ProductList.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>

@using PartsUnlimited

@if (Model == null || !Model.Any())
{
    <div class="alert alert-warning" role="alert">No products found!</div>
}
else
{
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <div class="list-item-part">
                    <a href="@Url.Action("Details", "Store", new {id = product.ProductId})" title="@product.Title">
                        <div class="product-image-container hover-over hidden-xs">
                            <div class="image">
                                <img src="/images/@product.ProductArtUrl" alt="@product.Title"/>
                            </div>
                            <div class="detail">
                                <h4>@product.Title</h4>
                                <h5>@product.Price.ToString("C")</h5>
                            </div>
                            <div class="mouse-over hidden-xs">
                                <div class="image-second">
                                    <img src="/images/@product.ProductArtUrl" alt="@product.Title zoom"/>
                                </div>

                                <div class="shop-now">
                                    <span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;<span>Shop Now</span>
                                </div>
                            </div>
                        </div>

                        <div class="row visible-xs">
                            <div class="col-xs-4 col-sm-12 col-md-12 no-gutter-sm no-gutter image">
                                <img src="/images/@product.ProductArtUrl" alt="@product.Title"/>
                    </div>
                            <div class="col-xs-8 col-sm-12 col-md-12 detail">
                                <h4>@product.Title</h4>
                                <h5>@product.Price.ToString("C")</h5>
                        </div>
                    </div>
                    </a>
                </div>
            </div>
        }
    </div>
}

Data/Module1-IntelligentApp/Source/Ex2/End/src/PartsUnlimitedWebsite/Views/Shared/_Recommendations.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>

@if (Model.Any())
{
        <h2>You may also consider</h2>
        @await Html.PartialAsync("_ProductList", Model)
}